services:

  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db_fintrack
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - net-fintrack

  adminer:
    image: adminer
    restart: always
    ports:
      - "8008:8080"
    networks:
      - net-fintrack

  redis:
    image: redis:8.0.1-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - net-fintrack

  api:
    image: mathasd/fintrack-api:2.0
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - net-fintrack
    restart: unless-stopped

volumes:
  db_data:
  redis_data:

networks:
  net-fintrack:
    driver: bridge