services:

  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db_fintrack
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgres
    networks:
      - net-fintrack

  adminer:
    image: adminer
    restart: always
    ports:
      - "8008:8080"
    networks:
      - net-fintrack

volumes:
  db_data:

networks:
  net-fintrack:
    driver: bridge