name: Dockerhub-image-upload

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-image-in-docker-hub:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: src/Dockerfile
          push: true
          tags: |
            mathasd/fintrack-api:v${{ github.run_number }}
            mathasd/fintrack-api:latest
